{{- if and .Values.feeds.github.token (not .Values.feeds.github.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slowshield.githubSecretName" . }}
  labels: {{- include "slowshield.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.feeds.github.existingSecretKey }}: {{ .Values.feeds.github.token | quote }}
{{- end }}
